name: 'Build development infrastructure to AWS'
on:
  push:
    branches:
      - 'dev'
jobs:
  cdk_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Install dependencies
        run: npm install
      - name: Generate .env.dev
        run: bash generate-env.sh -e dev -f .env.dev
      - name: Run tests
        run: npm run test
      - name: Deploy static webpage
        run: npm run deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
